export const FETCH = "fetch"
export const SUCCESS = "success"
export const GET_GALLERY_LIST = "get_gallery_list"
export const UPLOAD_IMAGE = "upload_image"
export const REORDER = "reorder"
export const ERROR = "error"